name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'canary'
        type: choice
        options:
          - latest
          - beta
          - canary

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: preview
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Setup Node.js (for npm registry)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run typecheck
        run: bun run typecheck

      - name: Build package
        run: bun run build

      - name: Version and publish memoose-js
        run: |
          if [ "${{ inputs.release_type }}" = "latest" ]; then
            echo "Publishing latest version..."
            bun pm version patch --no-git-tag-version
            bun publish --access public
          elif [ "${{ inputs.release_type }}" = "beta" ]; then
            echo "Publishing beta version..."
            bun pm version prerelease --preid=beta --no-git-tag-version
            bun publish --tag beta --access public
          else
            echo "Publishing canary version..."
            COMMIT_SHA=$(git rev-parse --short HEAD)
            CURRENT_VERSION=$(bun -e "console.log(require('./package.json').version)")
            BASE_VERSION=${CURRENT_VERSION%-canary.*}
            NEW_VERSION="${BASE_VERSION}-canary.${COMMIT_SHA}"
            bun pm pkg set version="${NEW_VERSION}"
            bun publish --tag canary --access public
          fi
          echo "Successfully published memoose-js"
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit and push version changes
        if: inputs.release_type == 'latest' || inputs.release_type == 'beta'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add package.json bun.lockb
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            if [ "${{ inputs.release_type }}" = "latest" ]; then
              git commit -m "chore: bump package version [skip ci]"
            else
              git commit -m "chore: bump beta version [skip ci]"
            fi
            git push
          fi